#!/usr/bin/env python3
"""Initialize executable sample cases, then optionally run them to produce genuine history."""
import argparse,json,os,time,urllib.request,uuid
p=argparse.ArgumentParser();p.add_argument('--base-url',default='http://127.0.0.1:8098');p.add_argument('--run',action='store_true');args=p.parse_args()
token=os.environ.get('WORKSPACE_TOKEN')
if not token:raise SystemExit('Set WORKSPACE_TOKEN to your user access token or private operator token; it is never printed.')
def call(path,body=None,key=None):
 headers={'Authorization':'Bearer '+token,'Content-Type':'application/json'}
 if key:headers['Idempotency-Key']=key
 req=urllib.request.Request(args.base_url.rstrip('/')+path,headers=headers,data=json.dumps(body).encode() if body is not None else None)
 with urllib.request.urlopen(req,timeout=30) as r:return json.load(r)
result=call('/api/automation/demo/seed',{})
print('Created',result['created'],'sample cases; total',len(result['cases']))
if args.run:
 for case in result['cases']:
  run=call('/api/automation/cases/'+case['id']+'/run',{},str(uuid.uuid4()));print(case['channel'],case['title'],'run',run['id'])
print('Demo cases are explicitly marked. Execution outcomes are generated by the real Runner, never prefilled.')
